Repository hyperskill-content/football-stats-final-project, pull requests merged in 2025-06, with the labels that each got.

#9 fix: Improve UI prompt consistency and readability
  src/main/java/com/hyperskill/managers/CoachStatisticsManager.java
  src/main/java/com/hyperskill/managers/PlayerManager.java
  src/main/java/com/hyperskill/managers/PlayerStatisticsManager.java
  src/main/java/com/hyperskill/managers/TeamManager.java
  src/main/java/com/hyperskill/managers/TeamStatisticsManager.java
  src/main/java/com/hyperskill/ui/SportsStatisticsInterface.java
Labels: documentation

#14 # Refactor coach selection functionality for better separation of con…
  src/main/java/com/hyperskill/managers/CoachManager.java
Labels: bug

#16 # Refactor player selection functionality for improved separation of …
  src/main/java/com/hyperskill/managers/PlayerManager.java
Labels: documentation

#23 Issue 17 update Person Player Coach
  build.gradle
  src/main/java/com/hyperskill/data_models/Coach.java
  src/main/java/com/hyperskill/data_models/Player.java
Labels: enhancement

#25 Issue#24: updated Match and Team classes
  src/main/java/com/hyperskill/data_models/Goal.java
  src/main/java/com/hyperskill/data_models/Match.java
  src/main/java/com/hyperskill/data_models/Team.java
Labels: enhancement

#32 Issue 26 create playerservice
  src/main/java/com/hyperskill/FootballStatisticsDB.java
  src/main/java/com/hyperskill/entity/Coach.java
  src/main/java/com/hyperskill/entity/Match.java
  src/main/java/com/hyperskill/entity/Person.java
  src/main/java/com/hyperskill/entity/Player.java
  src/main/java/com/hyperskill/entity/Team.java
  src/main/java/com/hyperskill/factory/CoachFactory.java
  src/main/java/com/hyperskill/factory/MatchFactory.java
  src/main/java/com/hyperskill/factory/PlayerFactory.java
  src/main/java/com/hyperskill/factory/SimpleCoachFactory.java
  src/main/java/com/hyperskill/factory/SimpleMatchFactory.java
  src/main/java/com/hyperskill/factory/SimplePlayerFactory.java
  src/main/java/com/hyperskill/factory/TeamFactory.java
  src/main/java/com/hyperskill/managers/CoachManager.java
  src/main/java/com/hyperskill/managers/CoachStatisticsManager.java
  src/main/java/com/hyperskill/managers/MatchManager.java
  src/main/java/com/hyperskill/managers/PlayerManager.java
  src/main/java/com/hyperskill/managers/PlayerStatisticsManager.java
  src/main/java/com/hyperskill/managers/TeamManager.java
  src/main/java/com/hyperskill/managers/TeamStatisticsManager.java
  src/main/java/com/hyperskill/repository/PlayerRepository.java
  src/main/java/com/hyperskill/repository/TeamRepository.java
  src/main/java/com/hyperskill/service/PlayerService.java
  src/main/java/com/hyperskill/statistics/CoachStatistics.java
  src/main/java/com/hyperskill/statistics/PlayerStatistics.java
  src/main/java/com/hyperskill/statistics/TeamStatistics.java
  src/main/java/com/hyperskill/utils/FootballDataLoader.java
  src/test/java/com/hyperskill/statistics/TeamStatisticsTest.java
Labels: enhancement

#41 commenting unused methods for compiling the app
  src/main/java/com/hyperskill/entity/Match.java
  src/main/java/com/hyperskill/entity/Team.java
  src/main/java/com/hyperskill/service/PlayerService.java
  src/main/java/com/hyperskill/statistics/CoachStatistics.java
  src/main/java/com/hyperskill/statistics/PlayerStatistics.java
  src/main/java/com/hyperskill/statistics/TeamStatistics.java
  src/main/resources/application.properties
Labels: bug

#43 feat: Populate database with initial teams, players, and matches data
  build.gradle
  src/main/resources/application.properties
  src/main/resources/data.sql
Labels: enhancement
